# Generated by Django 5.2.5 on 2025-08-20 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.CharField(max_length=255)),
                ('pid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='running', max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
