# Generated by Django 5.2.5 on 2025-08-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
