# Generated by Django 5.2.5 on 2025-08-20 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('tcp', 'Tcp'), ('udp', 'Udp')], max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'In'), ('outbound', 'Out')], max_length=10)),
                ('local_address', models.CharField(max_length=128)),
                ('remote_address', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], max_length=10)),
                ('more_info', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
