# Generated by Django 5.2.5 on 2025-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_hash_remove_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='bytes',
            field=models.PositiveIntegerField(default=2005),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='direction',
            field=models.CharField(choices=[('inbound', 'In'), ('outbound', 'Out')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
