# Generated by Django 5.2.5 on 2025-08-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='received',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
