# Generated by Django 5.2.5 on 2025-08-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_received_application_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='status',
        ),
    ]
