# Generated by Django 5.2.5 on 2025-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_connection_bytes_connection_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
