# Generated by Django 5.2.5 on 2025-08-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_connection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20),
        ),
    ]
