# Generated by Django 5.2.5 on 2025-08-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_connection_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='direction',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=20),
        ),
    ]
