# Generated by Django 5.2.5 on 2025-08-27 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0002_device_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('support', models.CharField(max_length=521)),
                ('kb', models.CharField(max_length=521)),
                ('mandatory', models.BooleanField(default=False)),
                ('reboot_required', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
