# Generated by Django 5.2.5 on 2025-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchmanagement',
            name='download_patch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patchmanagement',
            name='install_patch',
            field=models.BooleanField(default=False),
        ),
    ]
