# Generated by Django 5.2.5 on 2025-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0002_patchmanagement_download_patch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchmanagement',
            name='update_id',
            field=models.CharField(blank=True, max_length=521, null=True),
        ),
    ]
