# Generated by Django 5.2.5 on 2025-08-20 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_connection'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('TCP', 'Tcp'), ('UDP', 'Udp'), ('ANY', 'Any')], max_length=10)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('BOTH', 'Both')], max_length=10)),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block')], max_length=10)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosts.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block')], max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.device')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firewall.firewallrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
