# Generated by Django 5.2.5 on 2025-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
