# Generated by Django 5.2.5 on 2025-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='direction',
            field=models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound'), ('BOTH', 'Both')], max_length=10),
        ),
    ]
