# Generated by Django 5.2.5 on 2025-08-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentlog',
            name='timestamp',
        ),
    ]
